const CollectionTypes = {
	ADD_COLLECTION: "ADD_COLLECTION",
	FETCH_COLLECTION_START: "FETCH_COLLECTION_START",
	FETCH_COLLECTION_SUCCESS: "FETCH_COLLECTION_SUCCESS",
	FETCH_COLLECTION_FAILURE: "FETCH_COLLECTION_FAILURE",
};

export default CollectionTypes;
