const UserTypes = {
	SET_CURRENT_USER: "SET_CURRENT_USER",
	SET_USER_TOKEN: "SET_USER_TOKEN",
	LOGOUT_USER: "LOGOUT_USER",
	LOGIN_START: "LOGIN_START",
	LOGIN_SUCCESS: "LOGIN_SUCCESS",
	LOGIN_FAILURE: "LOGIN_FAILURE",
	SIGNUP_START: "SIGNUP_START",
	SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
	SIGNUP_FAILURE: "SIGNUP_FAILURE",
};

export default UserTypes;
